@baseUrl = http://localhost:5000

### Health check (optional)
GET {{baseUrl}}/

### Add a new student
POST {{baseUrl}}/student
Content-Type: application/json

{
  "name": "Sejal Shinkar",
  "score": 85,
  "category": "obc",
  "state": "Maharashtra"
}



### ✅ Get All Colleges
GET http://localhost:5000/colleges

### ✅ Get Eligible Colleges
GET http://localhost:5000/colleges/eligible-colleges?score=85&category=obc
